### ISSUE TITLE
Testmon very sensitive towards library changes

### ISSUE THREAD

**Issue by dgot** [tarpas/pytest-testmon#183]
## Background
I have found `pytest-testmon` to be very sensitive towards the slightest changes for the packages in the environment it is installed.
This makes it almost impossible to use `pytest-testmon` in practice when sharing a `.testmondata` file between our developers.

## Use Case:
A developer is trying out a new library `foo` and have written a wrapper `foo_bar.py` for this.
The developer only wants to run `test_foo_bar.py` for `foo_bar.py`, however the entire test suite is run since `foo`  was installed.

## Example Solution
Flag for disregarding library changes

> I am happy to contribute with a solution, if it is considered possible.
> If library needs funding for a solution, this is an option  as well.

**Comment by emavgl** [comment]
Could also be true for every changes in the requirements.txt?

**Comment by tarpas** [comment]
@dgot @emavgl 
Hello. I just pushed a beta version (install with pip `install --pre pytest-testmon`) which disregards changes of dependencies versions in the patch version number (after 2nd dot). Could you please try!?

**Comment by tarpas** [comment]
Please let me knnow if disregarding version after 2nd dot is practical enough.

**Comment by emavgl** [comment]
Hello! Unfortunately I don't have much time these days to try this out. Also, I am not currently using testmon at work. So, from my side, please feel free to merge the change.

**Comment by jacksongoode** [comment]
Sorry to be back one again with an issue, but the latest version is throwing.
`testmon: The packages installed in your Python environment have been changed. All tests have to be re-executed.`
in some cases and not skipping tests that haven't been changed in some case.

Our process is:
- Retrieve the last testmondata(-shm/wal) produced from running the last tests
- Use setup.py to read package & version from lock (we have a Pipfile => Pipfile.lock)
- Build wheel with setup.py
- Send wheel to a Databricks Spark cluster (a new Linux environment)
- Install the wheel
- Find that when tests are triggered with .testmondata, packages are wrong, or tests are not skipped.

**Comment by jmkolbe** [comment]
@jacksongoode in case you're still wondering, the setting is accepted in `pytest.ini` as `testmon_ignore_dependencies = '<package name>'`

It would not accept a list on my end. Not sure if that's by design, it would seem reasonable to want to pass a list there. Also, the message 
> The packages installed in your Python environment have been changed. All tests have to be re-executed
is still shown. 

But it does appear to fulfill the requirement, i.e. exempting specific installed packages when evaluating if the test run needs to be repeated 👍

**Comment by marcodicro-dp** [comment]
I'd also like this to be less sensitive. 

E.g. If I built the testmon db this morning doing a full test run, then a version change in an external library like e.g `google-cloud-bigquery` doesn't mean I have to run all the tests again if I made a simple code change.

I've tried adding that library to `testmon_ignore_dependencies` in pytest.ini without success:
```testmon_ignore_dependencies = 'google-cloud-bigquery'``` 

For this to work, does testmon_ignore_dependencies have to be set when the testmon DB is built too?

**Comment by uartie** [comment]
We really need a simple, single cli option way to disable this system lib check until testmon is refactored to be "smarter" about checking the "real" dependencies.  Afaict, if your tests/project doesn't "actually" depend on a system installed lib/package, testmon can't make that distinction... it assumes that everything that is installed is a dependency.
